import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
FACEBOOK_PAGE_ID = os.getenv("FB_PAGE_ID", os.getenv("FACEBOOK_PAGE_ID", "61589349864879"))
FACEBOOK_PAGE_ACCESS_TOKEN = os.getenv("FB_PAGE_TOKEN", os.getenv("FACEBOOK_PAGE_ACCESS_TOKEN"))
INSTAGRAM_BUSINESS_ACCOUNT_ID = os.getenv("INSTAGRAM_BUSINESS_ACCOUNT_ID")
X_BEARER_TOKEN = os.getenv("X_BEARER_TOKEN")
TIKTOK_ACCESS_TOKEN = os.getenv("TIKTOK_ACCESS_TOKEN")
TIKTOK_OPEN_ID = os.getenv("TIKTOK_OPEN_ID")
YOUTUBE_ACCESS_TOKEN = os.getenv("YOUTUBE_ACCESS_TOKEN")
THREADS_AUTH_TOKEN = os.getenv("THREADS_AUTH_TOKEN")
THREADS_USER_ID = os.getenv("THREADS_USER_ID")
